# app/routers/mail_share_certificate_issue.py
from __future__ import annotations

from pathlib import Path
from datetime import datetime
from email.message import EmailMessage
from typing import List, Optional, Tuple
import json, re, ssl, smtplib

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from ..settings import (
    COMPANIES_ROOT,
    EMAILS_ROOT,
    SMTP_SERVER,
    SMTP_PORT,
    SENDER_EMAIL,
    SENDER_PASSWORD,
    TEMPLATES_WORD_ROOT,
)
from ..utils.render_docx import _latest_master, build_context, render_docx

router = APIRouter(
    prefix="/api/mail",
    tags=["mail-share-certificate"],
)

BR_TEMPLATE_NAME = "Br_Share_Certificate_Issuance.docx"
EMAIL_TEMPLATE_NAME = "email_share_certificate_issue.html"


class ShareCertMailRequest(BaseModel):
    # company folder name exactly as it appears under /companies
    company_key: str
    # optional meeting / issue date for BR (YYYY-MM-DD or DD-MM-YYYY etc.)
    meeting_date: Optional[str] = None


# ---------- helpers ----------

def _safe(s: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", (s or "").strip()).strip("_").lower()


def _fmt_date(d: Optional[str]) -> str:
    """
    Normalise incoming 'meeting_date' into 'DD Mon YYYY'.
    Falls back to today if empty / unparsable.
    """
    if not d:
        return datetime.now().strftime("%d %b %Y")
    d = d.strip()
    for fmt in ("%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y", "%Y/%m/%d"):
        try:
            return datetime.strptime(d, fmt).strftime("%d %b %Y")
        except Exception:
            continue
    # last resort: just return raw
    return d


def _company_dir(company_key: str) -> Path:
    cdir = COMPANIES_ROOT / company_key
    if not cdir.exists():
        raise HTTPException(status_code=404, detail=f"Company folder not found: {cdir}")
    return cdir


def _find_master_json(company_dir: Path) -> Optional[Path]:
    """
    Like other mail routers – look for *_master_*.json in root or outputs/.
    """
    candidates: List[Path] = []

    candidates += list(company_dir.glob("_master_*.json"))

    outputs = company_dir / "outputs"
    if outputs.exists():
        candidates += list(outputs.glob("_master_*.json"))
        legacy = outputs / "master.json"
        if legacy.exists():
            candidates.append(legacy)

    print(f"[share_cert_mail] Searching for master JSON in {company_dir}")
    for c in candidates:
        print(f"[share_cert_mail]  candidate: {c}")

    if not candidates:
        return None

    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    latest = candidates[0]
    print(f"[share_cert_mail] Using master JSON: {latest}")
    return latest


def _load_email_template(filename: str) -> str:
    path = EMAILS_ROOT / filename
    print(f"[share_cert_mail] Loading email template: {path}")
    if not path.exists():
        raise FileNotFoundError(f"Email template not found: {path}")
    return path.read_text(encoding="utf-8")


def _render_template(raw_html: str, context: dict) -> str:
    """
    Very simple {{ placeholder }} replacement.
    """
    html = raw_html
    for key, value in context.items():
        value_str = "" if value is None else str(value)
        html = html.replace(f"{{{{ {key} }}}}", value_str)
        html = html.replace(f"{{{{{key}}}}}", value_str)
    return html


def _send_mail_with_attachments(
    subject: str,
    html_body: str,
    to: List[str],
    attachments: List[Path],
) -> None:
    print(f"[share_cert_mail] Preparing email to {to}, subject='{subject}'")

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = SENDER_EMAIL
    msg["To"] = ", ".join(to)

    msg.set_content("This is an HTML email. Please view it in an HTML-capable email client.")
    msg.add_alternative(html_body, subtype="html")

    for p in attachments:
        if not p.exists():
            print(f"[share_cert_mail] WARNING: attachment not found: {p}")
            continue
        data = p.read_bytes()
        msg.add_attachment(
            data,
            maintype="application",
            subtype="octet-stream",
            filename=p.name,
        )
        print(f"[share_cert_mail] Attached file: {p.name}")

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, context=context) as server:
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)

    print("[share_cert_mail] Email sent successfully.")


def _find_share_certificate_docs(company_dir: Path) -> List[Path]:
    """
    Find all share certificate DOCX generated by the share-certificate process.
    We assume filenames start with 'sharecert__'.
    """
    docs = sorted(
        company_dir.glob("sharecert__*.docx"),
        key=lambda p: p.stat().st_mtime,
    )
    print(f"[share_cert_mail] Found {len(docs)} share certificate DOCX in {company_dir}")
    return docs


def _generate_br_doc(company_key: str, meeting_date: Optional[str]) -> Path:
    """
    Render 'Br_Share_Certificate_Issuance.docx' for this company and date.
    """
    company_dir = _company_dir(company_key)
    master = _latest_master(company_dir)
    if not master:
        raise HTTPException(
            status_code=404,
            detail=f"Master JSON not found for company '{company_key}'",
        )

    ctx = build_context(master, explicit_date=meeting_date)
    if not isinstance(ctx, dict):
        ctx = dict(ctx or {})

    # Normalised meeting date, pushed into ctx.extra
    meeting_str = _fmt_date(meeting_date)
    extra = ctx.get("extra") or {}
    extra.setdefault("meeting_date", meeting_str)
    extra.setdefault("date", meeting_str)
    ctx["extra"] = extra

    # Ensure directors list is present from master JSON
    master_data = json.loads(Path(master).read_text(encoding="utf-8"))
    directors = master_data.get("directors") or ctx.get("directors") or []
    ctx["directors"] = directors

    tpl = TEMPLATES_WORD_ROOT / BR_TEMPLATE_NAME
    if not tpl.exists():
        raise HTTPException(
            status_code=500,
            detail=f"Board Resolution template not found: {tpl}",
        )

    tpl_id = f"br_share_certificate_{_safe(company_key)}"
    out_path = render_docx(tpl, company_dir, ctx, tpl_id)
    print(f"[share_cert_mail] Generated BR DOCX: {out_path}")
    return out_path


def _prepare_email_payload(
    payload: ShareCertMailRequest,
) -> Tuple[str, str, str, List[Path]]:
    """
    Build everything needed for preview/send:
    - recipient email
    - company name
    - rendered HTML body
    - attachments (all share certs + BR)
    """
    company_key = payload.company_key
    company_dir = _company_dir(company_key)

    master_json = _find_master_json(company_dir)
    if master_json is None:
        raise HTTPException(
            status_code=404,
            detail=f"Master JSON not found for company '{company_key}'",
        )

    data = json.loads(master_json.read_text(encoding="utf-8"))

    client_email = (
        data.get("client_email")
        or data.get("email")
        or data.get("client", {}).get("email")
    )
    if not client_email:
        raise HTTPException(
            status_code=400,
            detail="Client email not found in master JSON.",
        )

    company_name = (
        data.get("company_name")
        or data.get("company", {}).get("name")
        or company_key
    )

    share_docs = _find_share_certificate_docs(company_dir)
    if not share_docs:
        raise HTTPException(
            status_code=404,
            detail="No share certificate DOCX files (sharecert__*.docx) found in company folder.",
        )

    br_doc = _generate_br_doc(company_key, payload.meeting_date)
    attachments = share_docs + [br_doc]

    raw_html = _load_email_template(EMAIL_TEMPLATE_NAME)
    context = {
        "company_name": company_name,
        "client_email": client_email,
        "share_cert_count": len(share_docs),
        "br_filename": br_doc.name,
    }
    html_body = _render_template(raw_html, context)

    return client_email, company_name, html_body, attachments


# ---------- API endpoints ----------

@router.post("/preview/share-cert-issue")
def preview_share_certificate_issue(payload: ShareCertMailRequest):
    """
    Return rendered HTML body for preview. Does NOT send email.
    """
    to_email, company_name, html_body, attachments = _prepare_email_payload(payload)
    return {
        "ok": True,
        "to": to_email,
        "company": company_name,
        "html": html_body,
        "attachments": [p.name for p in attachments],
    }


@router.post("/send/share-cert-issue")
def send_share_certificate_issue_mail(payload: ShareCertMailRequest):
    """
    Send email to client with all share certificates and BR attached.
    """
    to_email, company_name, html_body, attachments = _prepare_email_payload(payload)

    subject = f"Share Certificate Issuance – {company_name}"
    _send_mail_with_attachments(
        subject=subject,
        html_body=html_body,
        to=[to_email],
        attachments=attachments,
    )

    return {
        "ok": True,
        "to": to_email,
        "company": company_name,
        "attached": [p.name for p in attachments],
    }
